/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  AccountFavorites: () => import('#controllers/account_favorites_controller'),
  AccountReviews: () => import('#controllers/account_reviews_controller'),
  AccountWatched: () => import('#controllers/account_watched_controller'),
  Genres: () => import('#controllers/genres_controller'),
  Movies: () => import('#controllers/movies_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Reviews: () => import('#controllers/reviews_controller'),
  UserFavorites: () => import('#controllers/user_favorites_controller'),
  UserReviews: () => import('#controllers/user_reviews_controller'),
  UserWatched: () => import('#controllers/user_watched_controller'),
  Users: () => import('#controllers/users_controller'),
}
