/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FavoriteSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'movieId', 'updatedAt', 'userId'] as const
  $columns = FavoriteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare movieId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class GenreSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = GenreSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MovieGenreSchema extends BaseModel {
  static $columns = ['genreId', 'id', 'movieId'] as const
  $columns = MovieGenreSchema.$columns
  @column()
  declare genreId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare movieId: number
}

export class MovieSchema extends BaseModel {
  static $columns = ['ageRating', 'bannerImageUrl', 'cast', 'contentWarning', 'createdAt', 'durationMinutes', 'id', 'posterImageUrl', 'releaseYear', 'synopsis', 'title', 'updatedAt'] as const
  $columns = MovieSchema.$columns
  @column()
  declare ageRating: string | null
  @column()
  declare bannerImageUrl: string | null
  @column()
  declare cast: string | null
  @column()
  declare contentWarning: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMinutes: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare posterImageUrl: string | null
  @column()
  declare releaseYear: number | null
  @column()
  declare synopsis: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReviewSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'movieId', 'rating', 'text', 'updatedAt', 'userId'] as const
  $columns = ReviewSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare movieId: number
  @column()
  declare rating: number
  @column()
  declare text: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WatchedMovieSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'movieId', 'updatedAt', 'userId'] as const
  $columns = WatchedMovieSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare movieId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}
