/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type GenreTransformer from '#transformers/genre_transformer'
import type MovieTransformer from '#transformers/movie_transformer'
import type ReviewTransformer from '#transformers/review_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Genre = InferData<GenreTransformer>
  export namespace Genre {
    export type Variants = InferVariants<GenreTransformer>
  }
  export type Movie = InferData<MovieTransformer>
  export namespace Movie {
    export type Variants = InferVariants<MovieTransformer>
  }
  export type Review = InferData<ReviewTransformer>
  export namespace Review {
    export type Variants = InferVariants<ReviewTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
